### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by tdwood397** [bretterer/home-assistant-rivian#101]
I am getting the following error when submitting username/password (or when submitting one time code when 2FA is enabled) during initial configuration. This only happens with correct credentials. This is version 0.10.0 installed via HACS.

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/rivian/config_flow.py:129 
Integration: Rivian (Unofficial) (documentation, issues) 
First occurred: 10:37:00 AM (1 occurrences) 
Last logged: 10:37:00 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/rivian/config_flow.py", line 110, in async_step_user
    return await self._async_create_entry()
  File "/config/custom_components/rivian/config_flow.py", line 129, in _async_create_entry
    entry_id = self.context["entry_id"]
KeyError: 'entry_id'
```

**Comment by geoeng** [comment]
I also just encountered this issue.

**Comment by tmack8001** [comment]
This is a logic flaw introduced in 0.10.0 release, the team will look at fixing this for a bugfix release soon.

In the meantime if you manually install/revert to an earlier release, configure with your username/password (optionally 2fa) and after a successful configuration and only then upgrade to 0.10.0 this is a proven workaround that will get past this issue for now.
