### ISSUE TITLE
Vehicle Images api is broken?

### ISSUE THREAD

**Issue by smazurov** [bretterer/home-assistant-rivian#175]
My dashboard no longer displays any images and I'm getting the following error with regards to vehicle images:

```
This error originated from a custom integration.

Logger: custom_components.rivian.coordinator
Source: custom_components/rivian/coordinator.py:77
integration: Rivian (Unofficial) (documentation, issues)
First occurred: 1:53:33 PM (1 occurrences)
Last logged: 1:53:33 PM

Rivian api exception: (200, {'errors': [{'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'reason': 'INTERNAL_SERVER_ERROR'}, 'message': 'Unexpected error occurred', 'path': ['getVehicleOrderMobileImages']}], 'data': None}, {'User-Agent': 'RivianApp/707 CFNetwork/1237 Darwin/20.4.0', 'Accept': 'application/json', 'Content-Type': 'application/json', 'Apollographql-Client-Name': 'com.rivian.ios.consumer-apollo-ios', 'A-Sess': '<snip>', 'U-Sess': '<snip>'}, {'operationName': 'getVehicleImages', 'query': 'query getVehicleImages( $extension: String $resolution: String $versionForVehicle: String $versionForPreOrder: String ) { getVehicleOrderMobileImages( resolution: $resolution extension: $extension version: $versionForPreOrder ) { ...image } getVehicleMobileImages( resolution: $resolution extension: $extension version: $versionForVehicle ) { ...image } } fragment image on VehicleMobileImage { orderId vehicleId url extension resolution size design placement overlays { url overlay zIndex } }', 'variables': {'extension': None, 'resolution': '@3x', 'versionForVehicle': '3', 'versionForPreOrder': None}})
Traceback (most recent call last):
  File "/config/custom_components/rivian/coordinator.py", line 77, in _async_update_data
    resp = await self._fetch_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rivian/coordinator.py", line 381, in _fetch_data
    data = await self.api.get_vehicle_images(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rivian/rivian.py", line 401, in get_vehicle_images
    return await self.__graphql_query(headers, url, graphql_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rivian/rivian.py", line 688, in __graphql_query
    raise exception
  File "/usr/local/lib/python3.12/site-packages/rivian/rivian.py", line 679, in __graphql_query
    raise err_cls(response.status, response_json, headers, body)
rivian.exceptions.RivianApiException: (200, {'errors': [{'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'reason': 'INTERNAL_SERVER_ERROR'}, 'message': 'Unexpected error occurred', 'path': ['getVehicleOrderMobileImages']}], 'data': None}, {'User-Agent': 'RivianApp/707 CFNetwork/1237 Darwin/20.4.0', 'Accept': 'application/json', 'Content-Type': 'application/json', 'Apollographql-Client-Name': 'com.rivian.ios.consumer-apollo-ios', 'A-Sess': '<snip>', 'U-Sess': '<snip>'}, {'operationName': 'getVehicleImages', 'query': 'query getVehicleImages( $extension: String $resolution: String $versionForVehicle: String $versionForPreOrder: String ) { getVehicleOrderMobileImages( resolution: $resolution extension: $extension version: $versionForPreOrder ) { ...image } getVehicleMobileImages( resolution: $resolution extension: $extension version: $versionForVehicle ) { ...image } } fragment image on VehicleMobileImage { orderId vehicleId url extension resolution size design placement overlays { url overlay zIndex } }', 'variables': {'extension': None, 'resolution': '@3x', 'versionForVehicle': '3', 'versionForPreOrder': None}})
```

in addition, this shows up as well:

```
Logger: homeassistant.helpers.entity_platform
Source: helpers/entity_platform.py:415
First occurred: 1:53:33 PM (1 occurrences)
Last logged: 1:53:33 PM

rivian raises exception ConfigEntryNotReady in forwarded platform image; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups
```

Worth nothing (perhaps) is that it started happening after upgrading `hacs` to `2.0.1`

**Comment by csmicfool** [comment]
Having same/similar issue since yesterday.

![image](https://github.com/user-attachments/assets/249a10c1-09eb-48da-8755-8c963b5c99f4)

![image](https://github.com/user-attachments/assets/8d65d044-a51e-4d52-868e-fa3a38a38a1f)

**Comment by bunjg** [comment]
Same issue, except I was running HACS for about a week before happened.  It started for me after losing internet for several days, then when I reloaded the integration the images were gone.
![image](https://github.com/user-attachments/assets/98ea9618-f31d-4543-b4b8-a7d0a76fe65d)
