### ISSUE TITLE
2nd vehicle updates stop after apparent network glitch

### ISSUE THREAD

**Issue by ditdafivo** [bretterer/home-assistant-rivian#186]
I have two vehicles on my account and have found after a while updates always stop for one of them, seemingly when a network glitch happens based on what I infer from debug logs. Updates for both seem to resume once I restart HA.

Here is a redacted/obfuscated version of 
[debug logs](https://github.com/user-attachments/files/18072502/home-assistant-4.log) showing the issue.  Below snip shows a series of apparent network errors impacting various components including rivian after timestamp 2024-12-07 23:31:34.390, then the only updates are to vehicle 01-926494020 and never again to vehicle 01-410746350.
```
2024-12-07 23:31:31.150 DEBUG (MainThread) [custom_components.rivian.coordinator] Vehicle 01-410746350 updated: <ALL-UPDATES-REDACTED>
2024-12-07 23:31:31.151 DEBUG (MainThread) [custom_components.rivian.coordinator] Manually updated rivian data
2024-12-07 23:31:34.389 DEBUG (MainThread) [custom_components.rivian.coordinator] Vehicle 01-410746350 updated: <ALL-UPDATES-REDACTED>
2024-12-07 23:31:34.390 DEBUG (MainThread) [custom_components.rivian.coordinator] Manually updated rivian data
2024-12-08 00:13:07.994 DEBUG (MainThread) [rivian.ws_monitor] WSMessage(type=<WSMsgType.TEXT: 1>, data='{"id":"<REDACTED>","type":"error","payload":[{"message":"fetch failed"}]}', extra='')
2024-12-08 02:30:52.505 ERROR (Thread-5) [pychromecast.socket_client] [Kitchen display(192.168.230.12):8009] Error reading from socket: socket connection broken
2024-12-08 02:30:52.512 ERROR (Thread-5) [pychromecast.socket_client] [Kitchen display(192.168.230.12):8009] Failed to connect to service HostServiceInfo(host='192.168.230.12', port=8009), retrying in 5.0s
2024-12-08 03:00:03.294 ERROR (MainThread) [homeassistant.components.shell_command] Error running command: `curl --digest -u admin:admin http://ata.local/rebootgetconfig.htm`, return code: 7
NoneType: None
2024-12-08 04:06:25.962 ERROR (Thread-6) [pychromecast.socket_client] [Rec Room Chromecast(192.168.128.117):8009] Failed to connect to service HostServiceInfo(host='192.168.128.117', port=8009), retrying in 5.0s
2024-12-08 04:49:39.168 ERROR (SyncWorker_29) [custom_components.solaredge_modbus] Error reading modbus data
Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 244, in _refresh_modbus_data
    update_result = self.read_modbus_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solaredge_modbus/__init__.py", line 318, in read_modbus_data
    self.read_modbus_data_inverter()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 686, in read_modbus_data_inverter
    self.data["acenergy"] = round(acenergy * 0.001, 3)
                                  ~~~~~~~~~^~~~~~~
OverflowError: int too large to convert to float
2024-12-08 05:20:11.252 DEBUG (MainThread) [custom_components.rivian.coordinator] Vehicle 01-926494020 updated: <ALL-UPDATES-REDACTED>
2024-12-08 05:20:11.254 DEBUG (MainThread) [custom_components.rivian.coordinator] Manually updated rivian data
2024-12-08 05:20:12.804 DEBUG (MainThread) [custom_components.rivian.coordinator] Vehicle 01-926494020 updated: <ALL-UPDATES-REDACTED>
2024-12-08 05:20:12.805 DEBUG (MainThread) [custom_components.rivian.coordinator] Manually updated rivian data
```

**Comment by bretterer** [comment]
@ditdafivo thanks for reporting this. We will take a look at this and see if we can find the issue. 

Is there anything that you can do in order to resolve this from your end?  Have you tried re-configuring the extension?

I am not sure if anyone on the team has two vehicles honestly, so this may be a little hard to debug but we will do our best!


cc: @natekspencer
