### ISSUE TITLE
Error setting up

### ISSUE THREAD

**Issue by OverZealous** [bretterer/home-assistant-rivian#2]
Hey there! Really awesome building this, I'm excited to get our Rivian integrated.

I tried setting it up, copying CLIENT_ID and CLIENT_SECRET from the local script I have (which works). When I try to set it up, I get "Unknown Error", and the logs show this:

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/rivian/config_flow.py:84
Integration: rivian (documentation)
First occurred: 12:35:52 PM (2 occurrences)
Last logged: 12:40:23 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/rivian/config_flow.py", line 84, in async_step_user
    self._access_token = json_data["access_token"]
UnboundLocalError: local variable 'json_data' referenced before assignment
```

I'd try to tackle it, but I'm not a Python developer. But let me know if I can test anything for you, including modifying the code manually to see if that works.

Thanks!

-----

Edit: I tried a few things to resolve this, but no luck:

1. Moving `json_data = await auth.json()` above the error check returned a different error (I believe this said something about `async` being invalid for a `dict`, but the error is gone after restarting HA)
2. Removing the `if auth.status == 401:` (and correcting the indent) returned a different error (`KeyError: 'session_token'`)
3. I tried logging in on a browser that wasn't logged into Rivian (just in case), no change on the original error.

**Comment by bretterer** [comment]
Things to check.  Right now, you are required to have MFA enabled on your Rivian Account. Without it, you will get some errors during the setup.  

Secondly, make sure you are using the correct username (should be email). This caught me a few times where I was just using username, instead of email

**Comment by OverZealous** [comment]
Ah, it's the lack of MFA, that makes sense. I'll look into setting it up.

**Comment by OverZealous** [comment]
Worked great! Thanks! I already have it set up and got my battery automation in.

**Comment by bretterer** [comment]
Thats great to hear!  Mind sharing your automation to show off what you are doing with it?
